W0731 14:48:29.093000 99768 site-packages/torch/distributed/run.py:793] 
W0731 14:48:29.093000 99768 site-packages/torch/distributed/run.py:793] *****************************************
W0731 14:48:29.093000 99768 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0731 14:48:29.093000 99768 site-packages/torch/distributed/run.py:793] *****************************************
Traceback (most recent call last):
  File "/media/jxiang9143/AIDataset/github/Video-3D-LLM/llava/train/train_grpo.py", line 24, in <module>
    from trainer import Qwen2VLGRPOTrainer, Qwen2VLGRPOVLLMTrainerModified
ModuleNotFoundError: No module named 'trainer'
Traceback (most recent call last):
  File "/media/jxiang9143/AIDataset/github/Video-3D-LLM/llava/train/train_grpo.py", line 24, in <module>
    from trainer import Qwen2VLGRPOTrainer, Qwen2VLGRPOVLLMTrainerModified
ModuleNotFoundError: No module named 'trainer'
Traceback (most recent call last):
  File "/media/jxiang9143/AIDataset/github/Video-3D-LLM/llava/train/train_grpo.py", line 24, in <module>
    from trainer import Qwen2VLGRPOTrainer, Qwen2VLGRPOVLLMTrainerModified
ModuleNotFoundError: No module named 'trainer'
Traceback (most recent call last):
  File "/media/jxiang9143/AIDataset/github/Video-3D-LLM/llava/train/train_grpo.py", line 24, in <module>
    from trainer import Qwen2VLGRPOTrainer, Qwen2VLGRPOVLLMTrainerModified
ModuleNotFoundError: No module named 'trainer'
W0731 14:48:31.600000 99768 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 99796 closing signal SIGTERM
E0731 14:48:31.616000 99768 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 99794) of binary: /home/jxiang9143/anaconda3/envs/video-r1/bin/python3.11
Traceback (most recent call last):
  File "/home/jxiang9143/anaconda3/envs/video-r1/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jxiang9143/anaconda3/envs/video-r1/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jxiang9143/anaconda3/envs/video-r1/lib/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/jxiang9143/anaconda3/envs/video-r1/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/jxiang9143/anaconda3/envs/video-r1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxiang9143/anaconda3/envs/video-r1/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llava/train/train_grpo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-07-31_14:48:31
  host      : ENG-AE-E058608
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 99795)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-07-31_14:48:31
  host      : ENG-AE-E058608
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 99797)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-31_14:48:31
  host      : ENG-AE-E058608
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 99794)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
